### ISSUE TITLE
ReportBuilder class

### ISSUE THREAD

**Issue by nexonpos** [hschneid/xfvrp#12]
Hello,, 
how can i find ReportBuilder class

**Comment by hschneid** [comment]
Hi,

I found it out:

There is no ReportBuilder. The Report.class contains the data and with the get methods it returns the aggregated data.

Greets

Holger

**Comment by HolgerSchneider** [comment]
Hi nexonpos,

in last release I added the report builder. For any reason it got lost.

Now the project can be build again. :-)

Greets

**Comment by hschneid** [comment]
Works now. :-)
