### ISSUE TITLE
Deploy 11.4.1 to Maven

### ISSUE THREAD

**Issue by larsupb** [hschneid/xfvrp#29]
Could you please invoke deployment of 11.4.1 to maven repository?

**Comment by hschneid** [comment]
Why not newest version 11.4.4?

**Comment by larsupb** [comment]
Oh never mind. Then just let’s proceed with 11.4.4🙂

**Comment by hschneid** [comment]
Release of 11.4.4 is done. It should be visible in maven central in next hours.

**Comment by larsupb** [comment]
Not really there :-( deployment process working?

**Comment by hschneid** [comment]
It is public:
https://search.maven.org/artifact/com.github.hschneid/xfvrp/11.4.4-RELEASE/jar
